# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'belt_screen.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGroupBox, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QRadioButton, QSizePolicy, QStatusBar, QTabWidget,
    QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(980, 1060)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(980, 1060))
        MainWindow.setMaximumSize(QSize(980, 16777215))
        palette = QPalette()
        brush = QBrush(QColor(76, 76, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush1 = QBrush(QColor(255, 255, 255, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette.setBrush(QPalette.Active, QPalette.Link, brush)
        brush2 = QBrush(QColor(65, 65, 218, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.LinkVisited, brush2)
        brush3 = QBrush(QColor(76, 76, 255, 10))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush3)
        palette.setBrush(QPalette.Active, QPalette.Accent, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        brush4 = QBrush(QColor(248, 248, 248, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush4)
        brush5 = QBrush(QColor(243, 243, 243, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush5)
        brush6 = QBrush(QColor(70, 70, 236, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Link, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush)
        brush7 = QBrush(QColor(227, 227, 227, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush7)
        brush8 = QBrush(QColor(68, 68, 68, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush8)
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush)
        MainWindow.setPalette(palette)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        palette1 = QPalette()
        self.centralwidget.setPalette(palette1)
        self.centralwidget.setStyleSheet(u"QPushButton::hover {\n"
"	background-color: rgb(69, 69, 232);\n"
"}")
        self.transmissions = QTabWidget(self.centralwidget)
        self.transmissions.setObjectName(u"transmissions")
        self.transmissions.setGeometry(QRect(20, 10, 941, 991))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.transmissions.sizePolicy().hasHeightForWidth())
        self.transmissions.setSizePolicy(sizePolicy1)
        self.transmissions.setTabPosition(QTabWidget.TabPosition.North)
        self.transmissions.setElideMode(Qt.TextElideMode.ElideLeft)
        self.transmissions.setTabsClosable(False)
        self.belt = QWidget()
        self.belt.setObjectName(u"belt")
        self.calculateButton = QPushButton(self.belt)
        self.calculateButton.setObjectName(u"calculateButton")
        self.calculateButton.setGeometry(QRect(760, 900, 151, 51))
        font = QFont()
        font.setFamilies([u"Syne"])
        font.setPointSize(12)
        font.setWeight(QFont.DemiBold)
        self.calculateButton.setFont(font)
        self.calculateButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.calculateButton.setAutoFillBackground(False)
        self.calculateButton.setStyleSheet(u"border: 2px solid;\n"
"border-radius: 6px;\n"
"background-color: rgb(76, 76, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgba(255, 255, 255, 0);")
        self.groupBox = QGroupBox(self.belt)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 110, 911, 381))
        font1 = QFont()
        font1.setFamilies([u"Merriweather"])
        font1.setPointSize(12)
        font1.setWeight(QFont.Medium)
        self.groupBox.setFont(font1)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(600, 100, 121, 16))
        font2 = QFont()
        font2.setFamilies([u"Syne"])
        font2.setPointSize(12)
        self.label_9.setFont(font2)
        self.label_9.setToolTipDuration(1000)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 30, 211, 16))
        self.label_4.setFont(font2)
        self.rev1Input = QLineEdit(self.groupBox)
        self.rev1Input.setObjectName(u"rev1Input")
        self.rev1Input.setGeometry(QRect(20, 50, 280, 31))
        palette2 = QPalette()
        self.rev1Input.setPalette(palette2)
        font3 = QFont()
        font3.setFamilies([u"Merriweather"])
        font3.setPointSize(10)
        font3.setBold(True)
        font3.setItalic(False)
        self.rev1Input.setFont(font3)
        self.rev1Input.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.rev1Input.setFrame(True)
        self.rev1Input.setClearButtonEnabled(True)
        self.rev2Input = QLineEdit(self.groupBox)
        self.rev2Input.setObjectName(u"rev2Input")
        self.rev2Input.setGeometry(QRect(20, 120, 280, 31))
        palette3 = QPalette()
        self.rev2Input.setPalette(palette3)
        self.rev2Input.setFont(font3)
        self.rev2Input.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.rev2Input.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.rev2Input.setClearButtonEnabled(True)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 100, 251, 16))
        self.label_5.setFont(font2)
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(310, 100, 211, 16))
        self.label_7.setFont(font2)
        self.pitchInput = QLineEdit(self.groupBox)
        self.pitchInput.setObjectName(u"pitchInput")
        self.pitchInput.setGeometry(QRect(600, 120, 141, 31))
        palette4 = QPalette()
        self.pitchInput.setPalette(palette4)
        self.pitchInput.setFont(font3)
        self.pitchInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.pitchInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.pitchInput.setClearButtonEnabled(True)
        self.powerInput = QLineEdit(self.groupBox)
        self.powerInput.setObjectName(u"powerInput")
        self.powerInput.setGeometry(QRect(310, 50, 280, 31))
        palette5 = QPalette()
        self.powerInput.setPalette(palette5)
        self.powerInput.setFont(font3)
        self.powerInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.powerInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.powerInput.setClearButtonEnabled(True)
        self.factorInput = QLineEdit(self.groupBox)
        self.factorInput.setObjectName(u"factorInput")
        self.factorInput.setGeometry(QRect(600, 50, 280, 31))
        palette6 = QPalette()
        self.factorInput.setPalette(palette6)
        self.factorInput.setFont(font3)
        self.factorInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.factorInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.factorInput.setClearButtonEnabled(True)
        self.smallPulleySelect = QRadioButton(self.groupBox)
        self.smallPulleySelect.setObjectName(u"smallPulleySelect")
        self.smallPulleySelect.setGeometry(QRect(750, 110, 141, 20))
        palette7 = QPalette()
        self.smallPulleySelect.setPalette(palette7)
        self.smallPulleySelect.setFont(font2)
        self.smallPulleySelect.setToolTipDuration(1000)
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(310, 30, 181, 16))
        self.label_6.setFont(font2)
        self.centerInput = QLineEdit(self.groupBox)
        self.centerInput.setObjectName(u"centerInput")
        self.centerInput.setGeometry(QRect(310, 120, 280, 31))
        palette8 = QPalette()
        self.centerInput.setPalette(palette8)
        self.centerInput.setFont(font3)
        self.centerInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.centerInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.centerInput.setClearButtonEnabled(True)
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(600, 30, 141, 16))
        self.label_8.setFont(font2)
        self.bigPulleySelect = QRadioButton(self.groupBox)
        self.bigPulleySelect.setObjectName(u"bigPulleySelect")
        self.bigPulleySelect.setGeometry(QRect(750, 130, 121, 20))
        palette9 = QPalette()
        self.bigPulleySelect.setPalette(palette9)
        self.bigPulleySelect.setFont(font2)
        self.bigPulleySelect.setToolTipDuration(1000)
        self.beltLengthInput = QLineEdit(self.groupBox)
        self.beltLengthInput.setObjectName(u"beltLengthInput")
        self.beltLengthInput.setGeometry(QRect(20, 190, 280, 31))
        palette10 = QPalette()
        self.beltLengthInput.setPalette(palette10)
        self.beltLengthInput.setFont(font3)
        self.beltLengthInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.beltLengthInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.beltLengthInput.setClearButtonEnabled(True)
        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 170, 241, 16))
        self.label_10.setFont(font2)
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(310, 170, 141, 16))
        self.label_11.setFont(font2)
        self.ratedPowerInput = QLineEdit(self.groupBox)
        self.ratedPowerInput.setObjectName(u"ratedPowerInput")
        self.ratedPowerInput.setGeometry(QRect(310, 190, 280, 31))
        palette11 = QPalette()
        self.ratedPowerInput.setPalette(palette11)
        self.ratedPowerInput.setFont(font3)
        self.ratedPowerInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.ratedPowerInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.ratedPowerInput.setClearButtonEnabled(True)
        self.addPowerInput = QLineEdit(self.groupBox)
        self.addPowerInput.setObjectName(u"addPowerInput")
        self.addPowerInput.setGeometry(QRect(600, 190, 280, 31))
        palette12 = QPalette()
        self.addPowerInput.setPalette(palette12)
        self.addPowerInput.setFont(font3)
        self.addPowerInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.addPowerInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.addPowerInput.setClearButtonEnabled(True)
        self.label_12 = QLabel(self.groupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(600, 170, 171, 16))
        self.label_12.setFont(font2)
        self.contactFactorInput = QLineEdit(self.groupBox)
        self.contactFactorInput.setObjectName(u"contactFactorInput")
        self.contactFactorInput.setGeometry(QRect(20, 260, 280, 31))
        palette13 = QPalette()
        self.contactFactorInput.setPalette(palette13)
        self.contactFactorInput.setFont(font3)
        self.contactFactorInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.contactFactorInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.contactFactorInput.setClearButtonEnabled(True)
        self.label_14 = QLabel(self.groupBox)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(310, 240, 231, 16))
        self.label_14.setFont(font2)
        self.powerFactorInput = QLineEdit(self.groupBox)
        self.powerFactorInput.setObjectName(u"powerFactorInput")
        self.powerFactorInput.setGeometry(QRect(310, 260, 280, 31))
        palette14 = QPalette()
        self.powerFactorInput.setPalette(palette14)
        self.powerFactorInput.setFont(font3)
        self.powerFactorInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.powerFactorInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.powerFactorInput.setClearButtonEnabled(True)
        self.label_15 = QLabel(self.groupBox)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 240, 271, 16))
        self.label_15.setFont(font2)
        self.instAllowanceInput = QLineEdit(self.groupBox)
        self.instAllowanceInput.setObjectName(u"instAllowanceInput")
        self.instAllowanceInput.setGeometry(QRect(600, 260, 281, 31))
        palette15 = QPalette()
        self.instAllowanceInput.setPalette(palette15)
        self.instAllowanceInput.setFont(font3)
        self.instAllowanceInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.instAllowanceInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.instAllowanceInput.setClearButtonEnabled(True)
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(600, 240, 161, 16))
        self.label_13.setFont(font2)
        self.label_13.setToolTipDuration(5)
        self.takeAllowanceInput = QLineEdit(self.groupBox)
        self.takeAllowanceInput.setObjectName(u"takeAllowanceInput")
        self.takeAllowanceInput.setGeometry(QRect(310, 330, 281, 31))
        palette16 = QPalette()
        self.takeAllowanceInput.setPalette(palette16)
        self.takeAllowanceInput.setFont(font3)
        self.takeAllowanceInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.takeAllowanceInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.takeAllowanceInput.setClearButtonEnabled(True)
        self.label_16 = QLabel(self.groupBox)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(310, 310, 131, 16))
        self.label_16.setFont(font2)
        self.label_16.setToolTipDuration(5)
        self.beltWeightInput = QLineEdit(self.groupBox)
        self.beltWeightInput.setObjectName(u"beltWeightInput")
        self.beltWeightInput.setGeometry(QRect(20, 330, 280, 31))
        palette17 = QPalette()
        self.beltWeightInput.setPalette(palette17)
        self.beltWeightInput.setFont(font3)
        self.beltWeightInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.beltWeightInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.beltWeightInput.setClearButtonEnabled(True)
        self.label_17 = QLabel(self.groupBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 310, 111, 16))
        self.label_17.setFont(font2)
        self.crossBelt = QCheckBox(self.groupBox)
        self.crossBelt.setObjectName(u"crossBelt")
        self.crossBelt.setGeometry(QRect(600, 330, 111, 20))
        font4 = QFont()
        font4.setFamilies([u"Syne"])
        font4.setPointSize(12)
        font4.setWeight(QFont.Medium)
        self.crossBelt.setFont(font4)
        self.crossBelt.setToolTipDuration(1000)
        self.label_18 = QLabel(self.groupBox)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(600, 310, 171, 16))
        self.label_18.setFont(font2)
        self.label_18.setToolTipDuration(5)
        self.resultText = QTextEdit(self.belt)
        self.resultText.setObjectName(u"resultText")
        self.resultText.setGeometry(QRect(10, 500, 721, 451))
        palette18 = QPalette()
        self.resultText.setPalette(palette18)
        font5 = QFont()
        font5.setFamilies([u"Merriweather"])
        font5.setPointSize(12)
        self.resultText.setFont(font5)
        self.resultText.viewport().setProperty("cursor", QCursor(Qt.CursorShape.ArrowCursor))
        self.resultText.setStyleSheet(u".eq-c {\n"
"  text-align: center;\n"
"  padding: 0em 0em;\n"
"  font-size: 2rem;\n"
"}\n"
"\n"
".eq-c .radical {\n"
"  font-size: 3.6rem;\n"
"  vertical-align: middle;\n"
"  margin: 0;\n"
"  padding: 0;\n"
"  right: -0.8rem;\n"
"}\n"
"\n"
".eq-c .radicand {\n"
"  top: 0.4rem;\n"
"  padding: 0 0.5rem;\n"
"  border-top: 0.2rem black solid;\n"
"}\n"
"\n"
".eq-c sup {\n"
"  font-size: 75%;\n"
"}\n"
"\n"
".fraction {\n"
"  display: inline-block;\n"
"  vertical-align: middle;\n"
"  margin: 0 0.2em 0.4ex;\n"
"  text-align: center;\n"
"}\n"
"\n"
".fraction > span {\n"
"  display: block;\n"
"  padding-top: 0.15em;\n"
"}\n"
"\n"
".fraction span.fdn {\n"
"  border-top: thin solid black;\n"
"}\n"
"\n"
".fraction span.bar {\n"
"  display: none;\n"
"}\n"
"\n"
".sy {\n"
"  position: relative;\n"
"  text-align: center;\n"
"}\n"
"\n"
".oncapital, .onsmall {\n"
"  position: absolute;\n"
"  top: -0.8em;\n"
"  left: 0px;\n"
"  width: 100%;\n"
"  font-size: 70%;\n"
"  text-align: center;\n"
"}\n"
"\n"
".onsmall {\n"
"  top: -0.5em"
                        ";\n"
"}\n"
"\n"
"")
        self.resultText.setAutoFormatting(QTextEdit.AutoFormattingFlag.AutoAll)
        self.resultText.setReadOnly(True)
        self.resultText.setAcceptRichText(True)
        self.resultText.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByKeyboard|Qt.TextInteractionFlag.LinksAccessibleByMouse|Qt.TextInteractionFlag.TextBrowserInteraction|Qt.TextInteractionFlag.TextSelectableByKeyboard|Qt.TextInteractionFlag.TextSelectableByMouse)
        self.Subtitle_2 = QLabel(self.belt)
        self.Subtitle_2.setObjectName(u"Subtitle_2")
        self.Subtitle_2.setGeometry(QRect(150, 30, 601, 81))
        font6 = QFont()
        font6.setFamilies([u"Syne"])
        font6.setPointSize(12)
        font6.setKerning(True)
        self.Subtitle_2.setFont(font6)
        self.Subtitle_2.setLineWidth(1)
        self.Subtitle_2.setTextFormat(Qt.TextFormat.AutoText)
        self.nextButton = QPushButton(self.belt)
        self.nextButton.setObjectName(u"nextButton")
        self.nextButton.setEnabled(True)
        self.nextButton.setGeometry(QRect(760, 500, 151, 51))
        self.nextButton.setFont(font)
        self.nextButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.nextButton.setAutoFillBackground(False)
        self.nextButton.setStyleSheet(u"border: 1px solid;\n"
"border-radius: 6px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(76, 76, 255);\n"
"border-color: rgb(76, 76, 255);")
        self.nextButton.setAutoDefault(False)
        self.nextButton.setFlat(False)
        self.clearAllButton = QPushButton(self.belt)
        self.clearAllButton.setObjectName(u"clearAllButton")
        self.clearAllButton.setGeometry(QRect(760, 800, 151, 51))
        self.clearAllButton.setFont(font)
        self.clearAllButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.clearAllButton.setAutoFillBackground(False)
        self.clearAllButton.setStyleSheet(u"border: 1px solid;\n"
"border-radius: 6px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(76, 76, 255);\n"
"border-color: rgb(76, 76, 255);")
        self.Title_2 = QLabel(self.belt)
        self.Title_2.setObjectName(u"Title_2")
        self.Title_2.setGeometry(QRect(350, 20, 221, 16))
        font7 = QFont()
        font7.setFamilies([u"Merriweather"])
        font7.setPointSize(16)
        font7.setBold(True)
        self.Title_2.setFont(font7)
        self.clearInputButton = QPushButton(self.belt)
        self.clearInputButton.setObjectName(u"clearInputButton")
        self.clearInputButton.setGeometry(QRect(760, 600, 151, 51))
        self.clearInputButton.setFont(font)
        self.clearInputButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.clearInputButton.setAutoFillBackground(False)
        self.clearInputButton.setStyleSheet(u"border: 1px solid;\n"
"border-radius: 6px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(76, 76, 255);\n"
"border-color: rgb(76, 76, 255);")
        self.clearResultButton = QPushButton(self.belt)
        self.clearResultButton.setObjectName(u"clearResultButton")
        self.clearResultButton.setGeometry(QRect(760, 700, 151, 51))
        self.clearResultButton.setFont(font)
        self.clearResultButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.clearResultButton.setAutoFillBackground(False)
        self.clearResultButton.setStyleSheet(u"border: 1px solid;\n"
"border-radius: 6px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(76, 76, 255);\n"
"border-color: rgb(76, 76, 255);")
        self.transmissions.addTab(self.belt, "")
        self.chain = QWidget()
        self.chain.setObjectName(u"chain")
        self.chainCalculateButton = QPushButton(self.chain)
        self.chainCalculateButton.setObjectName(u"chainCalculateButton")
        self.chainCalculateButton.setGeometry(QRect(760, 1050, 151, 51))
        self.chainCalculateButton.setFont(font)
        self.chainCalculateButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.chainCalculateButton.setAutoFillBackground(False)
        self.chainCalculateButton.setStyleSheet(u"border: 2px solid;\n"
"border-radius: 6px;\n"
"background-color: rgb(76, 76, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgba(255, 255, 255, 0);")
        self.chainTitle = QLabel(self.chain)
        self.chainTitle.setObjectName(u"chainTitle")
        self.chainTitle.setGeometry(QRect(340, 20, 241, 16))
        self.chainTitle.setFont(font7)
        self.chainClearInputsBtn = QPushButton(self.chain)
        self.chainClearInputsBtn.setObjectName(u"chainClearInputsBtn")
        self.chainClearInputsBtn.setGeometry(QRect(760, 750, 151, 51))
        self.chainClearInputsBtn.setFont(font)
        self.chainClearInputsBtn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.chainClearInputsBtn.setAutoFillBackground(False)
        self.chainClearInputsBtn.setStyleSheet(u"border: 1px solid;\n"
"border-radius: 6px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(76, 76, 255);\n"
"border-color: rgb(76, 76, 255);")
        self.groupBox_2 = QGroupBox(self.chain)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 110, 911, 521))
        self.groupBox_2.setFont(font1)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.label_19 = QLabel(self.groupBox_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(600, 100, 221, 16))
        self.label_19.setFont(font2)
        self.label_19.setToolTipDuration(1000)
        self.label_20 = QLabel(self.groupBox_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(20, 30, 211, 16))
        self.label_20.setFont(font2)
        self.chainPitchInput = QLineEdit(self.groupBox_2)
        self.chainPitchInput.setObjectName(u"chainPitchInput")
        self.chainPitchInput.setGeometry(QRect(20, 50, 280, 31))
        palette19 = QPalette()
        self.chainPitchInput.setPalette(palette19)
        self.chainPitchInput.setFont(font3)
        self.chainPitchInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.chainPitchInput.setFrame(True)
        self.chainPitchInput.setClearButtonEnabled(True)
        self.plateDiameterInput = QLineEdit(self.groupBox_2)
        self.plateDiameterInput.setObjectName(u"plateDiameterInput")
        self.plateDiameterInput.setGeometry(QRect(20, 120, 280, 31))
        palette20 = QPalette()
        self.plateDiameterInput.setPalette(palette20)
        self.plateDiameterInput.setFont(font3)
        self.plateDiameterInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.plateDiameterInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.plateDiameterInput.setClearButtonEnabled(True)
        self.label_21 = QLabel(self.groupBox_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(20, 100, 211, 16))
        self.label_21.setFont(font2)
        self.label_22 = QLabel(self.groupBox_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(310, 100, 201, 16))
        self.label_22.setFont(font2)
        self.overallJointInput = QLineEdit(self.groupBox_2)
        self.overallJointInput.setObjectName(u"overallJointInput")
        self.overallJointInput.setGeometry(QRect(600, 120, 281, 31))
        palette21 = QPalette()
        self.overallJointInput.setPalette(palette21)
        self.overallJointInput.setFont(font3)
        self.overallJointInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.overallJointInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.overallJointInput.setClearButtonEnabled(True)
        self.betweenWidthInput = QLineEdit(self.groupBox_2)
        self.betweenWidthInput.setObjectName(u"betweenWidthInput")
        self.betweenWidthInput.setGeometry(QRect(310, 50, 280, 31))
        palette22 = QPalette()
        self.betweenWidthInput.setPalette(palette22)
        self.betweenWidthInput.setFont(font3)
        self.betweenWidthInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.betweenWidthInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.betweenWidthInput.setClearButtonEnabled(True)
        self.rollerDiameterInput = QLineEdit(self.groupBox_2)
        self.rollerDiameterInput.setObjectName(u"rollerDiameterInput")
        self.rollerDiameterInput.setGeometry(QRect(600, 50, 280, 31))
        palette23 = QPalette()
        self.rollerDiameterInput.setPalette(palette23)
        self.rollerDiameterInput.setFont(font3)
        self.rollerDiameterInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.rollerDiameterInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.rollerDiameterInput.setClearButtonEnabled(True)
        self.label_23 = QLabel(self.groupBox_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(310, 30, 231, 16))
        self.label_23.setFont(font2)
        self.innerWidthInput = QLineEdit(self.groupBox_2)
        self.innerWidthInput.setObjectName(u"innerWidthInput")
        self.innerWidthInput.setGeometry(QRect(310, 120, 280, 31))
        palette24 = QPalette()
        self.innerWidthInput.setPalette(palette24)
        self.innerWidthInput.setFont(font3)
        self.innerWidthInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.innerWidthInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.innerWidthInput.setClearButtonEnabled(True)
        self.label_24 = QLabel(self.groupBox_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(600, 30, 211, 16))
        self.label_24.setFont(font2)
        self.pinDiameterInput = QLineEdit(self.groupBox_2)
        self.pinDiameterInput.setObjectName(u"pinDiameterInput")
        self.pinDiameterInput.setGeometry(QRect(20, 190, 280, 31))
        palette25 = QPalette()
        self.pinDiameterInput.setPalette(palette25)
        self.pinDiameterInput.setFont(font3)
        self.pinDiameterInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.pinDiameterInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.pinDiameterInput.setClearButtonEnabled(True)
        self.label_25 = QLabel(self.groupBox_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(20, 170, 161, 16))
        self.label_25.setFont(font2)
        self.label_26 = QLabel(self.groupBox_2)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(310, 170, 141, 16))
        self.label_26.setFont(font2)
        self.tranversePitchInput = QLineEdit(self.groupBox_2)
        self.tranversePitchInput.setObjectName(u"tranversePitchInput")
        self.tranversePitchInput.setGeometry(QRect(310, 190, 280, 31))
        palette26 = QPalette()
        self.tranversePitchInput.setPalette(palette26)
        self.tranversePitchInput.setFont(font3)
        self.tranversePitchInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.tranversePitchInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.tranversePitchInput.setClearButtonEnabled(True)
        self.massInput = QLineEdit(self.groupBox_2)
        self.massInput.setObjectName(u"massInput")
        self.massInput.setGeometry(QRect(600, 190, 280, 31))
        palette27 = QPalette()
        self.massInput.setPalette(palette27)
        self.massInput.setFont(font3)
        self.massInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.massInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.massInput.setCursorMoveStyle(Qt.CursorMoveStyle.VisualMoveStyle)
        self.massInput.setClearButtonEnabled(True)
        self.label_27 = QLabel(self.groupBox_2)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(600, 170, 171, 16))
        self.label_27.setFont(font2)
        self.bearingAreaInput = QLineEdit(self.groupBox_2)
        self.bearingAreaInput.setObjectName(u"bearingAreaInput")
        self.bearingAreaInput.setGeometry(QRect(20, 260, 280, 31))
        palette28 = QPalette()
        self.bearingAreaInput.setPalette(palette28)
        self.bearingAreaInput.setFont(font3)
        self.bearingAreaInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.bearingAreaInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.bearingAreaInput.setClearButtonEnabled(True)
        self.label_28 = QLabel(self.groupBox_2)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(310, 240, 231, 16))
        self.label_28.setFont(font2)
        self.breakingLoadInput = QLineEdit(self.groupBox_2)
        self.breakingLoadInput.setObjectName(u"breakingLoadInput")
        self.breakingLoadInput.setGeometry(QRect(310, 260, 280, 31))
        palette29 = QPalette()
        self.breakingLoadInput.setPalette(palette29)
        self.breakingLoadInput.setFont(font3)
        self.breakingLoadInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.breakingLoadInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.breakingLoadInput.setClearButtonEnabled(True)
        self.label_29 = QLabel(self.groupBox_2)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(20, 240, 271, 16))
        self.label_29.setFont(font2)
        self.transmissionRatioInput = QLineEdit(self.groupBox_2)
        self.transmissionRatioInput.setObjectName(u"transmissionRatioInput")
        self.transmissionRatioInput.setGeometry(QRect(600, 260, 281, 31))
        palette30 = QPalette()
        self.transmissionRatioInput.setPalette(palette30)
        self.transmissionRatioInput.setFont(font3)
        self.transmissionRatioInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.transmissionRatioInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.transmissionRatioInput.setClearButtonEnabled(True)
        self.label_30 = QLabel(self.groupBox_2)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(600, 240, 161, 16))
        self.label_30.setFont(font2)
        self.label_30.setToolTipDuration(5)
        self.serviceFactorInput = QLineEdit(self.groupBox_2)
        self.serviceFactorInput.setObjectName(u"serviceFactorInput")
        self.serviceFactorInput.setGeometry(QRect(310, 330, 281, 31))
        palette31 = QPalette()
        self.serviceFactorInput.setPalette(palette31)
        self.serviceFactorInput.setFont(font3)
        self.serviceFactorInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.serviceFactorInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.serviceFactorInput.setClearButtonEnabled(True)
        self.label_31 = QLabel(self.groupBox_2)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(310, 310, 131, 16))
        self.label_31.setFont(font2)
        self.label_31.setToolTipDuration(5)
        self.teethInput = QLineEdit(self.groupBox_2)
        self.teethInput.setObjectName(u"teethInput")
        self.teethInput.setGeometry(QRect(600, 330, 131, 31))
        palette32 = QPalette()
        self.teethInput.setPalette(palette32)
        self.teethInput.setFont(font3)
        self.teethInput.setToolTipDuration(1000)
        self.teethInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.teethInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.teethInput.setClearButtonEnabled(True)
        self.label_32 = QLabel(self.groupBox_2)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(600, 310, 151, 16))
        self.label_32.setFont(font2)
        self.bigSprocketSelect = QRadioButton(self.groupBox_2)
        self.bigSprocketSelect.setObjectName(u"bigSprocketSelect")
        self.bigSprocketSelect.setGeometry(QRect(740, 340, 141, 20))
        palette33 = QPalette()
        self.bigSprocketSelect.setPalette(palette33)
        self.bigSprocketSelect.setFont(font2)
        self.bigSprocketSelect.setToolTipDuration(1000)
        self.smallSprocketSelect = QRadioButton(self.groupBox_2)
        self.smallSprocketSelect.setObjectName(u"smallSprocketSelect")
        self.smallSprocketSelect.setGeometry(QRect(740, 320, 161, 20))
        palette34 = QPalette()
        self.smallSprocketSelect.setPalette(palette34)
        self.smallSprocketSelect.setFont(font2)
        self.smallSprocketSelect.setToolTipDuration(1000)
        self.chainRatedPowerInput = QLineEdit(self.groupBox_2)
        self.chainRatedPowerInput.setObjectName(u"chainRatedPowerInput")
        self.chainRatedPowerInput.setGeometry(QRect(20, 330, 280, 31))
        palette35 = QPalette()
        self.chainRatedPowerInput.setPalette(palette35)
        self.chainRatedPowerInput.setFont(font3)
        self.chainRatedPowerInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.chainRatedPowerInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.chainRatedPowerInput.setClearButtonEnabled(True)
        self.label_33 = QLabel(self.groupBox_2)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(20, 310, 181, 16))
        self.label_33.setFont(font2)
        self.centerDistanceInput = QLineEdit(self.groupBox_2)
        self.centerDistanceInput.setObjectName(u"centerDistanceInput")
        self.centerDistanceInput.setGeometry(QRect(20, 400, 280, 31))
        palette36 = QPalette()
        self.centerDistanceInput.setPalette(palette36)
        self.centerDistanceInput.setFont(font3)
        self.centerDistanceInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.centerDistanceInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.centerDistanceInput.setClearButtonEnabled(True)
        self.label_34 = QLabel(self.groupBox_2)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(20, 380, 181, 16))
        self.label_34.setFont(font2)
        self.initialSagInput = QLineEdit(self.groupBox_2)
        self.initialSagInput.setObjectName(u"initialSagInput")
        self.initialSagInput.setGeometry(QRect(310, 400, 281, 31))
        palette37 = QPalette()
        self.initialSagInput.setPalette(palette37)
        self.initialSagInput.setFont(font3)
        self.initialSagInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.initialSagInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.initialSagInput.setClearButtonEnabled(True)
        self.label_35 = QLabel(self.groupBox_2)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(310, 380, 131, 16))
        self.label_35.setFont(font2)
        self.label_35.setToolTipDuration(5)
        self.chainRev1Input = QLineEdit(self.groupBox_2)
        self.chainRev1Input.setObjectName(u"chainRev1Input")
        self.chainRev1Input.setGeometry(QRect(600, 400, 281, 31))
        palette38 = QPalette()
        self.chainRev1Input.setPalette(palette38)
        self.chainRev1Input.setFont(font3)
        self.chainRev1Input.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.chainRev1Input.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.chainRev1Input.setClearButtonEnabled(True)
        self.label_36 = QLabel(self.groupBox_2)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(600, 380, 231, 16))
        self.label_36.setFont(font2)
        self.loadFactorInput = QLineEdit(self.groupBox_2)
        self.loadFactorInput.setObjectName(u"loadFactorInput")
        self.loadFactorInput.setGeometry(QRect(310, 470, 281, 31))
        palette39 = QPalette()
        self.loadFactorInput.setPalette(palette39)
        self.loadFactorInput.setFont(font3)
        self.loadFactorInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.loadFactorInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.loadFactorInput.setClearButtonEnabled(True)
        self.constantInput = QLineEdit(self.groupBox_2)
        self.constantInput.setObjectName(u"constantInput")
        self.constantInput.setGeometry(QRect(20, 470, 280, 31))
        palette40 = QPalette()
        self.constantInput.setPalette(palette40)
        self.constantInput.setFont(font3)
        self.constantInput.setStyleSheet(u"font: 700 10pt \"Merriweather\";")
        self.constantInput.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)
        self.constantInput.setClearButtonEnabled(True)
        self.label_55 = QLabel(self.groupBox_2)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(310, 450, 131, 16))
        self.label_55.setFont(font2)
        self.label_55.setToolTipDuration(5)
        self.label_56 = QLabel(self.groupBox_2)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(20, 450, 281, 16))
        self.label_56.setFont(font2)
        self.prevButton = QPushButton(self.chain)
        self.prevButton.setObjectName(u"prevButton")
        self.prevButton.setEnabled(True)
        self.prevButton.setGeometry(QRect(760, 650, 151, 51))
        self.prevButton.setFont(font)
        self.prevButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.prevButton.setAutoFillBackground(False)
        self.prevButton.setStyleSheet(u"border: 1px solid;\n"
"border-radius: 6px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(76, 76, 255);\n"
"border-color: rgb(76, 76, 255);")
        self.prevButton.setAutoDefault(False)
        self.prevButton.setFlat(False)
        self.chainSubtitle = QLabel(self.chain)
        self.chainSubtitle.setObjectName(u"chainSubtitle")
        self.chainSubtitle.setGeometry(QRect(60, 30, 791, 81))
        self.chainSubtitle.setFont(font6)
        self.chainSubtitle.setStyleSheet(u"line-height: 0.25;")
        self.chainSubtitle.setLineWidth(1)
        self.chainSubtitle.setTextFormat(Qt.TextFormat.AutoText)
        self.chainResults = QTextEdit(self.chain)
        self.chainResults.setObjectName(u"chainResults")
        self.chainResults.setGeometry(QRect(10, 650, 721, 451))
        palette41 = QPalette()
        self.chainResults.setPalette(palette41)
        self.chainResults.setFont(font5)
        self.chainResults.viewport().setProperty("cursor", QCursor(Qt.CursorShape.ArrowCursor))
        self.chainResults.setStyleSheet(u".eq-c {\n"
"  text-align: center;\n"
"  padding: 0em 0em;\n"
"  font-size: 2rem;\n"
"}\n"
"\n"
".eq-c .radical {\n"
"  font-size: 3.6rem;\n"
"  vertical-align: middle;\n"
"  margin: 0;\n"
"  padding: 0;\n"
"  right: -0.8rem;\n"
"}\n"
"\n"
".eq-c .radicand {\n"
"  top: 0.4rem;\n"
"  padding: 0 0.5rem;\n"
"  border-top: 0.2rem black solid;\n"
"}\n"
"\n"
".eq-c sup {\n"
"  font-size: 75%;\n"
"}\n"
"\n"
".fraction {\n"
"  display: inline-block;\n"
"  vertical-align: middle;\n"
"  margin: 0 0.2em 0.4ex;\n"
"  text-align: center;\n"
"}\n"
"\n"
".fraction > span {\n"
"  display: block;\n"
"  padding-top: 0.15em;\n"
"}\n"
"\n"
".fraction span.fdn {\n"
"  border-top: thin solid black;\n"
"}\n"
"\n"
".fraction span.bar {\n"
"  display: none;\n"
"}\n"
"\n"
".sy {\n"
"  position: relative;\n"
"  text-align: center;\n"
"}\n"
"\n"
".oncapital, .onsmall {\n"
"  position: absolute;\n"
"  top: -0.8em;\n"
"  left: 0px;\n"
"  width: 100%;\n"
"  font-size: 70%;\n"
"  text-align: center;\n"
"}\n"
"\n"
".onsmall {\n"
"  top: -0.5em"
                        ";\n"
"}")
        self.chainResults.setAutoFormatting(QTextEdit.AutoFormattingFlag.AutoAll)
        self.chainResults.setReadOnly(True)
        self.chainResults.setAcceptRichText(True)
        self.chainResults.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByKeyboard|Qt.TextInteractionFlag.LinksAccessibleByMouse|Qt.TextInteractionFlag.TextBrowserInteraction|Qt.TextInteractionFlag.TextSelectableByKeyboard|Qt.TextInteractionFlag.TextSelectableByMouse)
        self.chainClearResultsBtn = QPushButton(self.chain)
        self.chainClearResultsBtn.setObjectName(u"chainClearResultsBtn")
        self.chainClearResultsBtn.setGeometry(QRect(760, 850, 151, 51))
        self.chainClearResultsBtn.setFont(font)
        self.chainClearResultsBtn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.chainClearResultsBtn.setAutoFillBackground(False)
        self.chainClearResultsBtn.setStyleSheet(u"border: 1px solid;\n"
"border-radius: 6px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(76, 76, 255);\n"
"border-color: rgb(76, 76, 255);")
        self.chainClearAll = QPushButton(self.chain)
        self.chainClearAll.setObjectName(u"chainClearAll")
        self.chainClearAll.setGeometry(QRect(760, 950, 151, 51))
        self.chainClearAll.setFont(font)
        self.chainClearAll.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.chainClearAll.setAutoFillBackground(False)
        self.chainClearAll.setStyleSheet(u"border: 1px solid;\n"
"border-radius: 6px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(76, 76, 255);\n"
"border-color: rgb(76, 76, 255);")
        self.transmissions.addTab(self.chain, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 980, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.transmissions.setCurrentIndex(0)
        self.nextButton.setDefault(False)
        self.prevButton.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Belt Screen", None))
        self.calculateButton.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
#if QT_CONFIG(shortcut)
        self.calculateButton.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Return", None))
#endif // QT_CONFIG(shortcut)
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Inputs", None))
#if QT_CONFIG(tooltip)
        self.label_9.setToolTip(QCoreApplication.translate("MainWindow", u"Also select the pitch from the selection to the right", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.label_9.setWhatsThis(QCoreApplication.translate("MainWindow", u"Also select the pitch from the selection to the right", None))
#endif // QT_CONFIG(whatsthis)
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Pitch Diameter", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"No of rev. on drive shaft (<var>N<sub>1</sub></var>)", None))
        self.rev1Input.setText("")
        self.rev1Input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter drive shaft revolutions in rpm", None))
        self.rev2Input.setText("")
        self.rev2Input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter pump revolutions in rpm", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"No of rev. on centrifugal pump (<var>N<sub>2</sub></var>)", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Approx. Center distance (<var>C</var>)", None))
        self.pitchInput.setText("")
        self.pitchInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter pulley pitch", None))
        self.powerInput.setText("")
        self.powerInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter power on drive shaft in kW", None))
        self.factorInput.setText("")
        self.factorInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter service factor", None))
#if QT_CONFIG(tooltip)
        self.smallPulleySelect.setToolTip(QCoreApplication.translate("MainWindow", u"Enter pitch diameter in field to the left", None))
#endif // QT_CONFIG(tooltip)
        self.smallPulleySelect.setText(QCoreApplication.translate("MainWindow", u"Small pulley (d)", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Power on drive shaft (<var>P</var>)", None))
        self.centerInput.setText("")
        self.centerInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter distance between pulleys in mm", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Service Factor (<var>K</var>)", None))
#if QT_CONFIG(tooltip)
        self.bigPulleySelect.setToolTip(QCoreApplication.translate("MainWindow", u"Enter pitch diameter in field to the left", None))
#endif // QT_CONFIG(tooltip)
        self.bigPulleySelect.setText(QCoreApplication.translate("MainWindow", u"Big pulley (D)", None))
        self.beltLengthInput.setText("")
        self.beltLengthInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter belt length from table in mm", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Standard Belt Length (<var>L</var>)", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Rated Power", None))
        self.ratedPowerInput.setText("")
        self.ratedPowerInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter rated power in kW", None))
        self.addPowerInput.setText("")
        self.addPowerInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter additional power for speed ratio in kW", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Additional Power", None))
        self.contactFactorInput.setText("")
        self.contactFactorInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter arc of contact correctional factor", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Power Correctional Factor (<var>F<sub>L</sub></var>)", None))
        self.powerFactorInput.setText("")
        self.powerFactorInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter power correctional factor", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Arc of Contact Correctional Factor (<var>F<sub>A</sub></var>)", None))
        self.instAllowanceInput.setText("")
        self.instAllowanceInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter allowance in mm", None))
#if QT_CONFIG(tooltip)
        self.label_13.setToolTip(QCoreApplication.translate("MainWindow", u"Also select the pitch from the selection to the right", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.label_13.setWhatsThis(QCoreApplication.translate("MainWindow", u"Also select the pitch from the selection to the right", None))
#endif // QT_CONFIG(whatsthis)
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Installation allowance", None))
        self.takeAllowanceInput.setText("")
        self.takeAllowanceInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter allowance in mm", None))
#if QT_CONFIG(tooltip)
        self.label_16.setToolTip(QCoreApplication.translate("MainWindow", u"Also select the pitch from the selection to the right", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.label_16.setWhatsThis(QCoreApplication.translate("MainWindow", u"Also select the pitch from the selection to the right", None))
#endif // QT_CONFIG(whatsthis)
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Takeup allowance", None))
        self.beltWeightInput.setText("")
        self.beltWeightInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter belt weight", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Belt Weight (W)", None))
#if QT_CONFIG(tooltip)
        self.crossBelt.setToolTip(QCoreApplication.translate("MainWindow", u"Check this box if belt is cross type", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.crossBelt.setWhatsThis(QCoreApplication.translate("MainWindow", u"Check this box if belt is cross type", None))
#endif // QT_CONFIG(whatsthis)
        self.crossBelt.setText(QCoreApplication.translate("MainWindow", u"Cross Belt", None))
#if QT_CONFIG(tooltip)
        self.label_18.setToolTip(QCoreApplication.translate("MainWindow", u"Also select the pitch from the selection to the right", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.label_18.setWhatsThis(QCoreApplication.translate("MainWindow", u"Also select the pitch from the selection to the right", None))
#endif // QT_CONFIG(whatsthis)
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"*Check if belt is crossed", None))
        self.resultText.setMarkdown("")
        self.resultText.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Merriweather'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.Subtitle_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\" style=\"line-height:0.25\">Belt drives use a flexible belt and pulleys. The belt runs over the pulleys, transmitting</p><p align=\"center\" style=\"line-height:0.25\">power through friction. Belt drives are quieter and require less</p><p align=\"center\" style=\"line-height:0.25\">maintenance compared to chain drives.</p></body></html>", None))
        self.nextButton.setText(QCoreApplication.translate("MainWindow", u"Next Tab", None))
#if QT_CONFIG(shortcut)
        self.nextButton.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.clearAllButton.setText(QCoreApplication.translate("MainWindow", u"Clear All", None))
#if QT_CONFIG(shortcut)
        self.clearAllButton.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+C", None))
#endif // QT_CONFIG(shortcut)
        self.Title_2.setText(QCoreApplication.translate("MainWindow", u"Belt Drive Calculator", None))
        self.clearInputButton.setText(QCoreApplication.translate("MainWindow", u"Clear Inputs", None))
#if QT_CONFIG(shortcut)
        self.clearInputButton.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+I", None))
#endif // QT_CONFIG(shortcut)
        self.clearResultButton.setText(QCoreApplication.translate("MainWindow", u"Clear Results", None))
#if QT_CONFIG(shortcut)
        self.clearResultButton.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+R", None))
#endif // QT_CONFIG(shortcut)
        self.transmissions.setTabText(self.transmissions.indexOf(self.belt), QCoreApplication.translate("MainWindow", u"Belt Drive", None))
        self.chainCalculateButton.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
#if QT_CONFIG(shortcut)
        self.chainCalculateButton.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Return", None))
#endif // QT_CONFIG(shortcut)
        self.chainTitle.setText(QCoreApplication.translate("MainWindow", u"Chain Drive Calculator", None))
        self.chainClearInputsBtn.setText(QCoreApplication.translate("MainWindow", u"Clear Inputs", None))
#if QT_CONFIG(shortcut)
        self.chainClearInputsBtn.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+I", None))
#endif // QT_CONFIG(shortcut)
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Inputs", None))
#if QT_CONFIG(tooltip)
        self.label_19.setToolTip(QCoreApplication.translate("MainWindow", u"Also select the pitch from the selection to the right", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.label_19.setWhatsThis(QCoreApplication.translate("MainWindow", u"Also select the pitch from the selection to the right", None))
#endif // QT_CONFIG(whatsthis)
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Maximum overall joint (<var>A<sub>1</sub></var>, <var>A<sub>2</sub></var>)", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Pitch (<var>P</var>)", None))
        self.chainPitchInput.setText("")
        self.chainPitchInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter pitch in mm", None))
        self.plateDiameterInput.setText("")
        self.plateDiameterInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter plate maximum diameter in mm", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Plate maximum diameter (<var>D<sub>h</sub></var>)", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Inner width of the plate (<var>W<sub>i</sub></var>)", None))
        self.overallJointInput.setText("")
        self.overallJointInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter maximum overall joint in mm", None))
        self.betweenWidthInput.setText("")
        self.betweenWidthInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter width between inner plate in mm", None))
        self.rollerDiameterInput.setText("")
        self.rollerDiameterInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter maximum roller diameter in mm", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Width between inner plate (<var>W</var>)", None))
        self.innerWidthInput.setText("")
        self.innerWidthInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter inner width of the plate in mm", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Maximum roller diameter (<var>D<sub>r</sub></var>)", None))
        self.pinDiameterInput.setText("")
        self.pinDiameterInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter pin body diameter in mm", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Pin body diameter (<var>P<sub>b</sub></var>)", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Tranverse Pitch (<var>P<sub>t</sub></var>)", None))
        self.tranversePitchInput.setText("")
        self.tranversePitchInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter transverse pitch in mm", None))
        self.massInput.setText("")
        self.massInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter mass in kg/m2", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Mass (<var>m</var>)", None))
        self.bearingAreaInput.setText("")
        self.bearingAreaInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter bearing area in mm", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Breaking load (<var>Q</var>)", None))
        self.breakingLoadInput.setText("")
        self.breakingLoadInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter breaking load in N", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Bearing area (<var>A</var>)", None))
        self.transmissionRatioInput.setText("")
        self.transmissionRatioInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter transmission ratio", None))
#if QT_CONFIG(tooltip)
        self.label_30.setToolTip(QCoreApplication.translate("MainWindow", u"Also select the pitch from the selection to the right", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.label_30.setWhatsThis(QCoreApplication.translate("MainWindow", u"Also select the pitch from the selection to the right", None))
#endif // QT_CONFIG(whatsthis)
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Transmission ratio (<var>i</var>)", None))
        self.serviceFactorInput.setText("")
        self.serviceFactorInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter service factor", None))
#if QT_CONFIG(tooltip)
        self.label_31.setToolTip(QCoreApplication.translate("MainWindow", u"Also select the pitch from the selection to the right", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.label_31.setWhatsThis(QCoreApplication.translate("MainWindow", u"Also select the pitch from the selection to the right", None))
#endif // QT_CONFIG(whatsthis)
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Service Factor (<var>K<sub>s</sub></var>)", None))
#if QT_CONFIG(tooltip)
        self.teethInput.setToolTip(QCoreApplication.translate("MainWindow", u"Select the sprocket from the selection to the right", None))
#endif // QT_CONFIG(tooltip)
        self.teethInput.setText("")
        self.teethInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter no of teeth", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Number of teeth (<span style=\" font-style:italic;\">Z)</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.bigSprocketSelect.setToolTip(QCoreApplication.translate("MainWindow", u"Enter no of teeth", None))
#endif // QT_CONFIG(tooltip)
        self.bigSprocketSelect.setText(QCoreApplication.translate("MainWindow", u"Big sprocket (Z2)", None))
#if QT_CONFIG(tooltip)
        self.smallSprocketSelect.setToolTip(QCoreApplication.translate("MainWindow", u"Enter no of teeth", None))
#endif // QT_CONFIG(tooltip)
        self.smallSprocketSelect.setText(QCoreApplication.translate("MainWindow", u"Small sprocket (Z1)", None))
        self.chainRatedPowerInput.setText("")
        self.chainRatedPowerInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter rated power in kW", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Rated Power (<var>P<sub>r</sub></var>)", None))
        self.centerDistanceInput.setText("")
        self.centerDistanceInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter assumed center distance in mm", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Center Distance (<var>a<sub>p</sub></var>)", None))
        self.initialSagInput.setText("")
        self.initialSagInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter inital sag in mm", None))
#if QT_CONFIG(tooltip)
        self.label_35.setToolTip(QCoreApplication.translate("MainWindow", u"Also select the pitch from the selection to the right", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.label_35.setWhatsThis(QCoreApplication.translate("MainWindow", u"Also select the pitch from the selection to the right", None))
#endif // QT_CONFIG(whatsthis)
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Initial sag", None))
        self.chainRev1Input.setText("")
        self.chainRev1Input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter no of rev. in rpm", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"No of rev. on smaller sprocket (<var>n<sub>1</sub></var>)", None))
        self.loadFactorInput.setText("")
        self.loadFactorInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter load factor", None))
        self.constantInput.setText("")
        self.constantInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter constant", None))
#if QT_CONFIG(tooltip)
        self.label_55.setToolTip(QCoreApplication.translate("MainWindow", u"Also select the pitch from the selection to the right", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.label_55.setWhatsThis(QCoreApplication.translate("MainWindow", u"Also select the pitch from the selection to the right", None))
#endif // QT_CONFIG(whatsthis)
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"Load Factor (<var>K<sub>t</sub</var>)", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"Constant due to arrangement of drive (<var>K</var>)", None))
        self.prevButton.setText(QCoreApplication.translate("MainWindow", u"Previous Tab", None))
#if QT_CONFIG(shortcut)
        self.prevButton.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.chainSubtitle.setText(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Syne'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:25%;\">Chain drives use a metal chain and sprockets to transfer power. The chain wraps</p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:25%;\">around the sprockets, allowing for efficient power transmission, especially</p>\n"
"<p align=\"center\" style=\" margin-top:12"
                        "px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:25%;\">in applications requiring high torque and heavy loads. </p></body></html>", None))
        self.chainResults.setMarkdown("")
        self.chainResults.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Merriweather'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.chainClearResultsBtn.setText(QCoreApplication.translate("MainWindow", u"Clear Results", None))
#if QT_CONFIG(shortcut)
        self.chainClearResultsBtn.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+R", None))
#endif // QT_CONFIG(shortcut)
        self.chainClearAll.setText(QCoreApplication.translate("MainWindow", u"Clear All", None))
#if QT_CONFIG(shortcut)
        self.chainClearAll.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+C", None))
#endif // QT_CONFIG(shortcut)
        self.transmissions.setTabText(self.transmissions.indexOf(self.chain), QCoreApplication.translate("MainWindow", u"Chain Drive", None))
    # retranslateUi

